import type {Metadata} from "next";
import {IBM_Plex_Mono, IBM_Plex_Serif} from "next/font/google";
import "./globals.css";
import Image from "next/image";
import SlidingTextRotator from "@/app/components/SlidingTextRotator";
import Link from "next/link";

const ibmPlexSerif = IBM_Plex_Serif({
    variable: "--font-ibm-plex-serif",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
    variable: "--font-ibm-plex-mono",
    weight: ["400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${ibmPlexSerif.variable} ${ibmPlexMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col items-center">
        <nav className="bg-primary-900 dark:bg-gray-700 w-full py-4 px-16 border-accent-500 border-b-4">
            <div className="container mx-auto flex flex-wrap gap-2 items-center">
                <Link href="/" className="flex items-center">
                    <Image
                        src="/bracket-logo.png"
                        alt="Next.js logo"
                        width={32}
                        height={32}
                        priority
                    />
                </Link>
                <div className="flex items-end gap-4 flex-wrap">
                    <div>
                        <h1 className="text-3xl font-bold">Joseph Simpson</h1>
                        <h2 className="font-mono">Software Design, Development, and <SlidingTextRotator
                            items={[
                                "Problem Solving",
                                "Curiosity",
                                "Teaching",
                                "Systems",
                                "Wonder",
                                "Understanding",
                                "Architecture"]}
                        /></h2>
                    </div>
                </div>
            </div>
        </nav>
        <div className="w-full container mx-auto">
            {children}
        </div>
        </body>
        </html>
    );
}
